version: '3.9'

services:
  slice-db:  
    build: . 
    image: slice-db:v1
    container_name: slice-db
    ports:
      - "6379:6379"
    networks:
      - slice-db-networks

networks:
  slice-db-networks:
    